apiVersion: apps/v1
kind: Deployment
metadata:
  name: travelapp-deployment
  labels:
    app: travelapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travelapp
  template:
    metadata:
      labels:
        app: travelapp
    spec:
      containers:
      - name: travelapp
        image: travel_sosh:latest
        ports:
        - containerPort: 80
