apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-sosh-deployment
  labels:
    app: travel-sosh
spec:
  replicas: 3
  selector:
    matchLabels:
      app: travel-sosh
  template:
    metadata:
      labels:
        app: travel-sosh
    spec:
      containers:
      - name: travel-sosh
        image: travel_sosh:latest  # Replace with your ECR image URL
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "Travel2gether.settings"
        - name: ALLOWED_HOSTS
          value: "*"
        volumeMounts:
        - name: static-files
          mountPath: /app/staticfiles
        - name: media-files
          mountPath: /app/media
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
          requests:
            memory: "256Mi"
            cpu: "0.2"
      volumes:
      - name: static-files
        emptyDir: {}
      - name: media-files
        emptyDir: {}
