apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel2gether-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel_sosh
  template:
    metadata:
      labels:
        app: travel_sosh
    spec:
      containers:
        - name: x23183209-container
          image: 250738637992.dkr.ecr.eu-west-1.amazonaws.com/x23183209-multicloud:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  type: LoadBalancer
  selector:
    app: your-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
